Repository MOV-AI/frontend-npm-ide-ce, pull requests merged in 2022-08, with the labels that each got.

#227 FP-2008 : Composed the names of the subflow children on Tree View
  CHANGELOG.md
  src/plugins/views/editors/Flow/Components/FlowTopBar/FlowSearch.jsx
  src/plugins/views/editors/Flow/Components/Menus/ContainerMenu.jsx
  src/plugins/views/editors/Flow/Components/Menus/NodeMenu.jsx
  src/plugins/views/editors/Flow/Components/Menus/sub-components/MenuDetails.jsx
  src/plugins/views/editors/Flow/Components/interface/MainInterface.js
  src/plugins/views/editors/Flow/Constants/constants.js
  src/plugins/views/editors/Flow/Core/Graph/GraphTreeView.js
  src/plugins/views/editors/Flow/Core/Graph/GraphValidator.js
  src/plugins/views/editors/Flow/Core/Graph/Utils.js
Labels: bug

#229 FP-2013 : Added correct colors to nodes in tree view miniatures
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/TreeView/TreeNodePortLink.js
Labels: bug

#228 FP-2007 : Avoid recursive template rendering
  CHANGELOG.md
  src/i18n/languages/en.json
  src/i18n/languages/pt.json
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/BaseContainerNode.js
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/TreeView/TreeNode.js
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/TreeView/TreeNodeHeader.js
  src/plugins/views/editors/Flow/Core/Graph/GraphTreeView.js
Labels: bug

#226 FP-1993 : Tree View subflows now correctly update changes made to them
  CHANGELOG.md
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/TreeView/TreeNode.js
  src/plugins/views/editors/Flow/Components/Nodes/TreeView/TreeContainerNode.js
  src/plugins/views/editors/Flow/Core/Graph/GraphBase.js
  src/plugins/views/editors/Flow/Core/Graph/GraphTreeView.js
Labels: bug

#231 New release : Trigger new version
  .github/CODEOWNERS
Labels: release-candidate

#233 FP-2022 : Flows without subflows will be correctly rendered
  src/plugins/views/editors/Flow/Core/Graph/GraphTreeView.js
Labels: bug

#232 FP-1987 : Selecting a node will allow you to fade other links when over a link
  CHANGELOG.md
  src/plugins/views/editors/Flow/Components/Links/BaseLink.js
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/BaseNode.js
  src/plugins/views/editors/Flow/Components/Nodes/BaseNode/TreeView/TreeNode.js
  src/plugins/views/editors/Flow/Components/interface/InterfaceModes.js
  src/plugins/views/editors/Flow/Components/interface/canvas.js
  src/plugins/views/editors/Flow/Flow.jsx
  src/plugins/views/editors/Flow/events.js
Labels: bug, refactor
